/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Motorstep.c
**     Project     : Solindar
**     Processor   : MC9S08QE128CLK
**     Component   : BitsIO
**     Version     : Component 02.108, Driver 03.28, CPU db: 3.00.067
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2019-10-16, 12:27, # CodeGen: 15
**     Abstract    :
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**     Settings    :
**         Port name                   : PTD
**
**         Bit mask of the port        : $00F0
**         Number of bits/pins         : 4
**         Single bit numbers          : 0 to 3
**         Values range                : 0 to 15
**
**         Initial direction           : Output (direction can be changed)
**         Safe mode                   : yes
**         Initial output value        : 0 = 000H
**         Initial pull option         : off
**
**         Port data register          : PTDD      [$0006]
**         Port control register       : PTDDD     [$0007]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    56   |   PTD4_KBI2P4
**                    1      |    28   |   PTD5_KBI2P5
**                    2      |    27   |   PTD6_KBI2P6
**                    3      |    26   |   PTD7_KBI2P7
**             ----------------------------------------------------
**
**         Optimization for            : speed
**     Contents    :
**         GetDir - bool Motorstep_GetDir(void);
**         SetDir - void Motorstep_SetDir(bool Dir);
**         GetVal - byte Motorstep_GetVal(void);
**         PutVal - void Motorstep_PutVal(byte Val);
**         GetBit - bool Motorstep_GetBit(byte Bit);
**         PutBit - void Motorstep_PutBit(byte Bit, bool Val);
**         SetBit - void Motorstep_SetBit(byte Bit);
**         ClrBit - void Motorstep_ClrBit(byte Bit);
**         NegBit - void Motorstep_NegBit(byte Bit);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Motorstep.c
** @version 03.28
** @brief
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
*/         
/*!
**  @addtogroup Motorstep_module Motorstep module documentation
**  @{
*/         

/* MODULE Motorstep. */

#include "Motorstep.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  Motorstep_GetMsk (component BitsIO)
**
**     Description :
**         The method returns a bit mask which corresponds to the 
**         required bit position.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static const  byte Motorstep_Table[4U] = { /* Table of mask constants */
   0x10U, 0x20U, 0x40U, 0x80U
};

static byte Motorstep_GetMsk (byte PinIndex)
{
  return (byte)((PinIndex<4U) ? Motorstep_Table[PinIndex] : 0U); /* Check range and return appropriate bit mask */
}

/*
** ===================================================================
**     Method      :  Motorstep_GetVal (component BitsIO)
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 15)
** ===================================================================
*/
byte Motorstep_GetVal(void)
{
  return (byte)((getReg8(PTDD) & 0xF0U) >> 4U); /* Return port data */
}

/*
** ===================================================================
**     Method      :  Motorstep_PutVal (component BitsIO)
**     Description :
**         This method writes the new output value.
**           a) direction = Input  : sets the new output value;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes the value to the
**                                   appropriate pins
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 15)
**     Returns     : Nothing
** ===================================================================
*/
void Motorstep_PutVal(byte Val)
{
  Val = (byte)((Val & 0x0FU) << 4U);   /* Mask and shift output value */
  Shadow_PTD = (byte)((Shadow_PTD & 0x0FU) | Val); /* Set-up shadow variable */
  setReg8(PTDD, (getReg8(PTDD) & (byte)(~(byte)0xF0U)) | Val); /* Put masked value on port */
}

/*
** ===================================================================
**     Method      :  Motorstep_GetBit (component BitsIO)
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 3)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/
bool Motorstep_GetBit(byte Bit)
{
  byte const Mask = Motorstep_GetMsk(Bit); /* Temporary variable - bit mask to test */
  return (bool)(((getReg8(PTDD) & Mask) == Mask)? 1U: 0U); /* Test if specified bit of port register is set */
}

/*
** ===================================================================
**     Method      :  Motorstep_PutBit (component BitsIO)
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**           a) direction = Input  : sets the value of the specified
**                                   bit; this operation will be
**                                   shown on output after the
**                                   direction has been switched to
**                                   output (SetDir(TRUE);)
**           b) direction = Output : directly writes the value of the
**                                   bit to the appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 3)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
void Motorstep_PutBit(byte Bit, bool Val)
{
  byte const Mask = Motorstep_GetMsk(Bit); /* Temporary variable - put bit mask */
  if (Val) {
    setReg8Bits(PTDD, Mask);           /* [bit (Bit+4)]=0x01U */
    Shadow_PTD |= Mask;                /* Set appropriate bit in shadow variable */
  } else { /* !Val */
    clrReg8Bits(PTDD, Mask);           /* [bit (Bit+4)]=0x00U */
    Shadow_PTD &= (byte)~(byte)Mask;   /* Clear appropriate bit in shadow variable */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  Motorstep_ClrBit (component BitsIO)
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**           a) direction = Input  : sets the specified bit to "0";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   beenswitched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "0" to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
void Motorstep_ClrBit(byte Bit)
{
  byte const Mask = Motorstep_GetMsk(Bit); /* Temporary variable - set bit mask */
  clrReg8Bits(PTDD, Mask);             /* [bit (Bit+4)]=0x00U */
  Shadow_PTD &= (byte)~(byte)Mask;     /* Set appropriate bit in shadow variable */
}

/*
** ===================================================================
**     Method      :  Motorstep_SetBit (component BitsIO)
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**           a) direction = Input  : sets the specified bit to "1";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "1" to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
void Motorstep_SetBit(byte Bit)
{
  byte const Mask = Motorstep_GetMsk(Bit); /* Temporary variable - set bit mask */
  setReg8Bits(PTDD, Mask);             /* [bit (Bit+4)]=0x01U */
  Shadow_PTD |= Mask;                  /* Set appropriate bit in shadow variable */
}

/*
** ===================================================================
**     Method      :  Motorstep_NegBit (component BitsIO)
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**           a) direction = Input  : inverts the specified bit;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly inverts the value
**                                   of the appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
void Motorstep_NegBit(byte Bit)
{
  byte const Mask = Motorstep_GetMsk(Bit); /* Temporary variable - set bit mask */
  invertReg8Bits(PTDD, Mask);          /* [bit (Bit+4)]=invert */
  Shadow_PTD ^= Mask;                  /* Set appropriate bit in shadow variable */
}

/*
** ===================================================================
**     Method      :  Motorstep_GetDir (component BitsIO)
**     Description :
**         This method returns direction of the component.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the component (<false> or <true>)
**                      <false> = Input, <true> = Output
** ===================================================================
*/
/*
bool Motorstep_GetDir(void)

**  This method is implemented as a macro. See Motorstep.h file.  **
*/

/*
** ===================================================================
**     Method      :  Motorstep_SetDir (component BitsIO)
**     Description :
**         This method sets direction of the component.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Dir        - Direction to set (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
**     Returns     : Nothing
** ===================================================================
*/
void Motorstep_SetDir(bool Dir)
{
  if (Dir) {
    setReg8(PTDD, (getReg8(PTDD) & (byte)(~(byte)0xF0U)) | (Shadow_PTD & 0xF0U)); /* Put masked value on port */
    /* PTDDD: PTDDD7=1,PTDDD6=1,PTDDD5=1,PTDDD4=1 */
    setReg8Bits(PTDDD, 0xF0U);          
  } else { /* !Dir */
    /* PTDDD: PTDDD7=0,PTDDD6=0,PTDDD5=0,PTDDD4=0 */
    clrReg8Bits(PTDDD, 0xF0U);          
  } /* !Dir */
}


/* END Motorstep. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
